version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: testdb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  nominatim:
    image: mediagis/nominatim:4.5
    ports:
      - "8080:8080"
    environment:
      PBF_URL: https://download.geofabrik.de/europe/monaco-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/europe/monaco-updates/
      NOMINATIM_PASSWORD: very_secure_password
    volumes:
      - nominatim-data:/var/lib/postgresql/14/main
    networks:
      - app-network
    shm_size: 1gb

  web:
    build: .
    depends_on:
      mongodb:
        condition: service_healthy
      nominatim:
        condition: service_started
    environment:
      DATABASE_URL: mongodb://root:example@mongodb:27017/testdb
      NOMINATIM_URL: http://nominatim:8080/
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: >
      sh -c "sleep 1 && python /app/app.py"

volumes:
  mongo_data:
  nominatim-data:

networks:
  app-network:
